description: avgen-job

target:
#  name: spch-sing-am-e2e-eu
#  name: spch-sing-am-e2e-sc
#  name: gcrprojvc1

#  name: cogs-sing-shared-eu
#  name: cogs-sing-shared-sc
#  name: cogs-sing-shared-wu2
  name: msrresrchvc
  service: sing

environment:
  image:  j4ckl1u/open_sora:latest  # unset CUDA_VISIBLE_DEVICES

code:
  local_dir: ./

storage:
  blob_model:
    storage_account_name: tsstd01wus2
#    storage_account_name: tsstd01scus
#    storage_account_name: tsstd01wus3
    container_name: models
    mount_dir: /modelblob
    mount_options:
    - --file-cache-timeout-in-seconds=1800

jobs:
- command:
  - bash train_job.sh

  name: avgen-job
  mpi: true
  process_count_per_node: 8
#  sku: 2xND40r_v2
  sku: G8-A100
#  sku: 16xND40r_v2
#  priority: high  # Default: medium
#  sla_tier: Standard  # Default: premium
#  execution_mode: basic  # Default: basic
  submit_args:
    constraints:
    - tag: connectivityDomain
      type: uniqueConstraint
    env:
      HOROVOD_HIERARCHICAL_ALLREDUCE: 1
      MKL_THREADING_LAYER: GNU
      NCCL_ASYNC_ERROR_HANDLING: 1
      NCCL_DEBUG: INFO
      NCCL_IB_DISABLE: 0
      NCCL_IB_TIMEOUT: 22
      SINGULARITY_SKIP_NCCL_VALIDATION: "true"
      SHARED_MEMORY_PERCENT: 0.50
